//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginApp.DataComponents
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerTable
    {
        public int CstId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerEmail { get; set; }
        public long CustomerMobile { get; set; }
        public string Password { get; set; }
    }
}
