//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiComponents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageFile
    {
        public int EntryId { get; set; }
        public int PlaceId { get; set; }
        public string ImageSource { get; set; }
    
        public virtual TouristPlace TouristPlace { get; set; }
    }
}
